from __future__ import annotations

from enum import StrEnum


class MarketRegime(StrEnum):
    UNKNOWN = "UNKNOWN"
    TREND_UP = "TREND_UP"
    TREND_DOWN = "TREND_DOWN"
    RANGE = "RANGE"
    TRANSITION = "TRANSITION"


class StrategyType(StrEnum):
    TREND_CONTINUATION = "TREND_CONTINUATION"
    RANGE_REVERSION = "RANGE_REVERSION"
    BREAKOUT = "BREAKOUT"


class SetupState(StrEnum):
    IDLE = "IDLE"
    ARMED = "ARMED"
    TRIGGERED = "TRIGGERED"
    ORDER_PENDING = "ORDER_PENDING"
    OPEN = "OPEN"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class Side(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class OrderAction(StrEnum):
    OPEN = "OPEN"
    MODIFY = "MODIFY"
    CLOSE = "CLOSE"
    NONE = "NONE"


class Decision(StrEnum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    HOLD = "HOLD"
    OPEN = "OPEN"
    MODIFY = "MODIFY"
    CLOSE = "CLOSE"
    SKIP = "SKIP"


class ReasonCode(StrEnum):
    # System lifecycle
    CONFIG_VALID = "CONFIG_VALID"
    CONFIG_INVALID = "CONFIG_INVALID"
    CYCLE_STARTED = "CYCLE_STARTED"
    CYCLE_COMPLETED = "CYCLE_COMPLETED"
    NO_TRADE = "NO_TRADE"

    # Data validation
    DATA_VALID = "DATA_VALID"
    DATA_STALE = "DATA_STALE"
    HISTORY_INSUFFICIENT = "HISTORY_INSUFFICIENT"
    MARKET_DATA_MISSING = "MARKET_DATA_MISSING"
    MARKET_DATA_STALE = "MARKET_DATA_STALE"
    BARS_NOT_SEQUENTIAL = "BARS_NOT_SEQUENTIAL"
    NO_CLOSED_BARS = "NO_CLOSED_BARS"
    NO_NEW_M15_BAR = "NO_NEW_M15_BAR"
    NEW_M15_BAR = "NEW_M15_BAR"
    HEARTBEAT_STALE = "HEARTBEAT_STALE"
    BRIDGE_UNAVAILABLE = "BRIDGE_UNAVAILABLE"

    # Regime
    REGIME_UNKNOWN = "REGIME_UNKNOWN"
    REGIME_TRANSITION = "REGIME_TRANSITION"
    REGIME_TREND_UP_CONFIRMED = "REGIME_TREND_UP_CONFIRMED"
    REGIME_TREND_DOWN_CONFIRMED = "REGIME_TREND_DOWN_CONFIRMED"
    REGIME_RANGE_CONFIRMED = "REGIME_RANGE_CONFIRMED"
    REGIME_TRANSITION_CONFIRMED = "REGIME_TRANSITION_CONFIRMED"
    REGIME_UNCHANGED = "REGIME_UNCHANGED"

    # Trend strategy
    TREND_STRUCTURE_INVALID = "TREND_STRUCTURE_INVALID"
    PULLBACK_NOT_FOUND = "PULLBACK_NOT_FOUND"
    PULLBACK_INVALIDATED = "PULLBACK_INVALIDATED"
    TRIGGER_NOT_CONFIRMED = "TRIGGER_NOT_CONFIRMED"
    TREND_FILTERS_NOT_READY = "TREND_FILTERS_NOT_READY"
    TREND_BUY_SIGNAL = "TREND_BUY_SIGNAL"
    TREND_SELL_SIGNAL = "TREND_SELL_SIGNAL"
    NO_TREND_PULLBACK_CONFIRMATION = "NO_TREND_PULLBACK_CONFIRMATION"

    # Range strategy
    RANGE_TOUCHES_INSUFFICIENT = "RANGE_TOUCHES_INSUFFICIENT"
    RANGE_MIDDLE_NO_TRADE = "RANGE_MIDDLE_NO_TRADE"
    RANGE_FILTERS_NOT_READY = "RANGE_FILTERS_NOT_READY"
    RANGE_BUY_SIGNAL = "RANGE_BUY_SIGNAL"
    RANGE_SELL_SIGNAL = "RANGE_SELL_SIGNAL"
    NO_RANGE_BOUNDARY_REJECTION = "NO_RANGE_BOUNDARY_REJECTION"

    # Breakout strategy
    BREAKOUT_RETEST_PENDING = "BREAKOUT_RETEST_PENDING"
    FALSE_BREAKOUT = "FALSE_BREAKOUT"
    BREAKOUT_FILTERS_NOT_READY = "BREAKOUT_FILTERS_NOT_READY"
    BREAKOUT_BOX_PENDING = "BREAKOUT_BOX_PENDING"
    BREAKOUT_BUY_SIGNAL = "BREAKOUT_BUY_SIGNAL"
    BREAKOUT_SELL_SIGNAL = "BREAKOUT_SELL_SIGNAL"
    NO_BREAKOUT_TRIGGER = "NO_BREAKOUT_TRIGGER"

    # Price / spread
    PRICE_OVEREXTENDED = "PRICE_OVEREXTENDED"
    SPREAD_TOO_HIGH = "SPREAD_TOO_HIGH"
    SPREAD_POINTS_TOO_HIGH = "SPREAD_POINTS_TOO_HIGH"
    SPREAD_ATR_TOO_HIGH = "SPREAD_ATR_TOO_HIGH"

    # Stop / RR
    STOP_TOO_LARGE = "STOP_TOO_LARGE"
    REWARD_RISK_TOO_LOW = "REWARD_RISK_TOO_LOW"

    # Risk / limits
    RISK_ACCEPTED = "RISK_ACCEPTED"
    RISK_TRADING_DISABLED = "RISK_TRADING_DISABLED"
    RISK_LIVE_NOT_ENABLED = "RISK_LIVE_NOT_ENABLED"
    RISK_ACCOUNT_NOT_OK = "RISK_ACCOUNT_NOT_OK"
    RISK_POSITION_EXISTS = "RISK_POSITION_EXISTS"
    RISK_DAILY_TRADES_LIMIT = "RISK_DAILY_TRADES_LIMIT"
    RISK_CONSECUTIVE_LOSSES_LIMIT = "RISK_CONSECUTIVE_LOSSES_LIMIT"
    RISK_DAILY_LOSS_LIMIT = "RISK_DAILY_LOSS_LIMIT"
    RISK_COOLDOWN_ACTIVE = "RISK_COOLDOWN_ACTIVE"
    RISK_STOP_TOO_CLOSE = "RISK_STOP_TOO_CLOSE"
    RISK_STOP_TOO_FAR = "RISK_STOP_TOO_FAR"
    RISK_REWARD_TOO_LOW = "RISK_REWARD_TOO_LOW"
    RISK_LOT_INVALID = "RISK_LOT_INVALID"
    DAILY_LIMIT_REACHED = "DAILY_LIMIT_REACHED"
    POSITION_ALREADY_OPEN = "POSITION_ALREADY_OPEN"
    COMMAND_ALREADY_PENDING = "COMMAND_ALREADY_PENDING"
    ORDER_REJECTED_BY_BROKER = "ORDER_REJECTED_BY_BROKER"

    # Setup lifecycle
    NO_STRATEGY_FOR_REGIME = "NO_STRATEGY_FOR_REGIME"
    SETUP_CREATED = "SETUP_CREATED"
    SETUP_ARMED = "SETUP_ARMED"
    SETUP_TRIGGERED = "SETUP_TRIGGERED"
    SETUP_ORDER_PENDING = "SETUP_ORDER_PENDING"
    SETUP_OPEN = "SETUP_OPEN"
    SETUP_EXPIRED = "SETUP_EXPIRED"
    SETUP_CANCELLED = "SETUP_CANCELLED"
    SETUP_REJECTED = "SETUP_REJECTED"
    SETUP_CLOSED = "SETUP_CLOSED"

    # Execution
    ORDER_OPEN_BUILT = "ORDER_OPEN_BUILT"
    ORDER_MODIFY_BUILT = "ORDER_MODIFY_BUILT"
    ORDER_CLOSE_BUILT = "ORDER_CLOSE_BUILT"
    EXECUTION_PAPER_FILLED = "EXECUTION_PAPER_FILLED"
    EXECUTION_COMMAND_WRITTEN = "EXECUTION_COMMAND_WRITTEN"
    EXECUTION_DUPLICATE_COMMAND = "EXECUTION_DUPLICATE_COMMAND"
    ACK_ACCEPTED = "ACK_ACCEPTED"
    ACK_REJECTED = "ACK_REJECTED"
    ACK_IGNORED = "ACK_IGNORED"
    RECONCILED_WITH_BROKER = "RECONCILED_WITH_BROKER"

    # Management
    MANAGEMENT_NO_ACTION = "MANAGEMENT_NO_ACTION"
    BREAKEVEN_MOVE = "BREAKEVEN_MOVE"
    TRAILING_MOVE = "TRAILING_MOVE"
    TAKE_PROFIT_HIT = "TAKE_PROFIT_HIT"
    EXIT_REGIME_FLIP = "EXIT_REGIME_FLIP"
    EXIT_STOP_HIT = "EXIT_STOP_HIT"
    EXIT_MANUAL_CLOSE = "EXIT_MANUAL_CLOSE"
