from __future__ import annotations
from enum import StrEnum

class MarketRegime(StrEnum):
    UNKNOWN="UNKNOWN"; TREND_UP="TREND_UP"; TREND_DOWN="TREND_DOWN"; RANGE="RANGE"; BREAKOUT="BREAKOUT"; TRANSITION="TRANSITION"
class StrategyType(StrEnum):
    BREAKOUT="BREAKOUT"; TREND_CONTINUATION="TREND_CONTINUATION"; RANGE_REVERSION="RANGE_REVERSION"
class SetupState(StrEnum):
    CANDIDATE="CANDIDATE"; WAITING_CONFIRMATION="WAITING_CONFIRMATION"; READY="READY"; TRIGGERED="TRIGGERED"; EXPIRED="EXPIRED"; CANCELLED="CANCELLED"
class Side(StrEnum):
    LONG="LONG"; SHORT="SHORT"
class OrderAction(StrEnum):
    OPEN="OPEN"; MODIFY="MODIFY"; CLOSE="CLOSE"; NONE="NONE"
class Decision(StrEnum):
    ALLOW="ALLOW"; BLOCK="BLOCK"; HOLD="HOLD"; OPEN="OPEN"; MODIFY="MODIFY"; CLOSE="CLOSE"; SKIP="SKIP"
class ReasonCode(StrEnum):
    CONFIG_VALID="CONFIG_VALID"; CONFIG_INVALID="CONFIG_INVALID"; CYCLE_STARTED="CYCLE_STARTED"; CYCLE_COMPLETED="CYCLE_COMPLETED"
    DATA_VALID="DATA_VALID"; MARKET_DATA_MISSING="MARKET_DATA_MISSING"; MARKET_DATA_STALE="MARKET_DATA_STALE"; BARS_NOT_SEQUENTIAL="BARS_NOT_SEQUENTIAL"; NO_CLOSED_BARS="NO_CLOSED_BARS"
    NO_NEW_M15_BAR="NO_NEW_M15_BAR"; NEW_M15_BAR="NEW_M15_BAR"; HEARTBEAT_STALE="HEARTBEAT_STALE"; BRIDGE_UNAVAILABLE="BRIDGE_UNAVAILABLE"
    REGIME_TREND_UP_CONFIRMED="REGIME_TREND_UP_CONFIRMED"; REGIME_TREND_DOWN_CONFIRMED="REGIME_TREND_DOWN_CONFIRMED"; REGIME_RANGE_CONFIRMED="REGIME_RANGE_CONFIRMED"; REGIME_TRANSITION_CONFIRMED="REGIME_TRANSITION_CONFIRMED"; REGIME_UNCHANGED="REGIME_UNCHANGED"
    TREND_FILTERS_NOT_READY="TREND_FILTERS_NOT_READY"; TREND_LONG_SIGNAL="TREND_LONG_SIGNAL"; TREND_SHORT_SIGNAL="TREND_SHORT_SIGNAL"; NO_TREND_PULLBACK_CONFIRMATION="NO_TREND_PULLBACK_CONFIRMATION"
    RANGE_FILTERS_NOT_READY="RANGE_FILTERS_NOT_READY"; RANGE_LONG_SIGNAL="RANGE_LONG_SIGNAL"; RANGE_SHORT_SIGNAL="RANGE_SHORT_SIGNAL"; NO_RANGE_BOUNDARY_REJECTION="NO_RANGE_BOUNDARY_REJECTION"
    BREAKOUT_FILTERS_NOT_READY="BREAKOUT_FILTERS_NOT_READY"; BREAKOUT_BOX_PENDING="BREAKOUT_BOX_PENDING"; BREAKOUT_LONG_SIGNAL="BREAKOUT_LONG_SIGNAL"; BREAKOUT_SHORT_SIGNAL="BREAKOUT_SHORT_SIGNAL"; NO_BREAKOUT_TRIGGER="NO_BREAKOUT_TRIGGER"
    NO_STRATEGY_FOR_REGIME="NO_STRATEGY_FOR_REGIME"; SETUP_CREATED="SETUP_CREATED"; SETUP_WAITING_CONFIRMATION="SETUP_WAITING_CONFIRMATION"; SETUP_CONFIRMED="SETUP_CONFIRMED"; SETUP_TRIGGERED="SETUP_TRIGGERED"; SETUP_EXPIRED="SETUP_EXPIRED"; SETUP_CANCELLED="SETUP_CANCELLED"
    RISK_ACCEPTED="RISK_ACCEPTED"; RISK_TRADING_DISABLED="RISK_TRADING_DISABLED"; RISK_LIVE_NOT_ENABLED="RISK_LIVE_NOT_ENABLED"; RISK_ACCOUNT_NOT_OK="RISK_ACCOUNT_NOT_OK"; RISK_POSITION_EXISTS="RISK_POSITION_EXISTS"
    RISK_DAILY_TRADES_LIMIT="RISK_DAILY_TRADES_LIMIT"; RISK_CONSECUTIVE_LOSSES_LIMIT="RISK_CONSECUTIVE_LOSSES_LIMIT"; RISK_COOLDOWN_ACTIVE="RISK_COOLDOWN_ACTIVE"; RISK_STOP_TOO_CLOSE="RISK_STOP_TOO_CLOSE"; RISK_STOP_TOO_FAR="RISK_STOP_TOO_FAR"; RISK_REWARD_TOO_LOW="RISK_REWARD_TOO_LOW"; RISK_LOT_INVALID="RISK_LOT_INVALID"
    SPREAD_POINTS_TOO_HIGH="SPREAD_POINTS_TOO_HIGH"; SPREAD_ATR_TOO_HIGH="SPREAD_ATR_TOO_HIGH"
    ORDER_OPEN_BUILT="ORDER_OPEN_BUILT"; ORDER_MODIFY_BUILT="ORDER_MODIFY_BUILT"; ORDER_CLOSE_BUILT="ORDER_CLOSE_BUILT"; EXECUTION_PAPER_FILLED="EXECUTION_PAPER_FILLED"; EXECUTION_COMMAND_WRITTEN="EXECUTION_COMMAND_WRITTEN"; EXECUTION_DUPLICATE_COMMAND="EXECUTION_DUPLICATE_COMMAND"
    ACK_ACCEPTED="ACK_ACCEPTED"; ACK_REJECTED="ACK_REJECTED"; ACK_IGNORED="ACK_IGNORED"; RECONCILED_WITH_BROKER="RECONCILED_WITH_BROKER"
    MANAGEMENT_NO_ACTION="MANAGEMENT_NO_ACTION"; BREAKEVEN_MOVE="BREAKEVEN_MOVE"; TRAILING_MOVE="TRAILING_MOVE"; TAKE_PROFIT_HIT="TAKE_PROFIT_HIT"; EXIT_REGIME_FLIP="EXIT_REGIME_FLIP"; EXIT_STOP_HIT="EXIT_STOP_HIT"; EXIT_MANUAL_CLOSE="EXIT_MANUAL_CLOSE"
